### ISSUE TITLE
vertical alignment

### ISSUE THREAD

**Issue by b87401116** [moshi4/phyTreeViz#1]
Hi, @moshi4,
Thank you for this sharing. I like this work since it can be integrated into other components in matplotlib. I wonder if the tree visualization can be produced in vertical alignment. Although it may be handled after producing the image, it will be more integratable if other component in matplotlib will be added onto the same axes.
  
thanks a lot

YC

**Comment by moshi4** [comment]
Hi @b87401116,

phyTreeViz only allows tree plots in the horizontal direction.

I think adding vertical tree plotting functionality is a good idea, but implementing that functionality in phyTreeViz is quite cumbersome. Therefore, I am not currently considering implementing a vertical tree plot feature. 
I am sorry that I could not meet your request.
