### ISSUE TITLE
Layout error (none is not a valid value)

### ISSUE THREAD

**Issue by mgalland** [moshi4/phyTreeViz#5]
Hello @moshi4 
Thank you for the nice wrapper package. Keeps it simple compared to the full fetch ete package.

When I run the example code, I obtain a ValueError regarding the layout option (from matplotlib probably). The error is 

ValueError: 'none' is not a valid value for layout; supported values are 'constrained', 'tight'

This is the example code I run:
```
from phytreeviz import TreeViz, load_example_tree_file

tree_file = load_example_tree_file("small_example.nwk")

tv = TreeViz(tree_file)
tv.show_branch_length(color="red")
tv.show_confidence(color="blue")
tv.show_scale_bar()

fig = tv.plotfig()
```

Could you have a look at this issue? 
Thank you
Marc

**Comment by moshi4** [comment]
Hi @mgalland,

The error appears to be caused by an old version of matplotlib, please update matplotlib to the latest version.
